server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/deliverydb
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update

# Not create Hibernate logs
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# KAFKA
spring.kafka.producer.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

spring.kafka.producer.properties.spring.json.type.mapping=delivery-placed-event:com.algaworks.algadelivery.delivery.tracking.domain.event.DeliveryPlacedEvent,delivery-picked-up-event:com.algaworks.algadelivery.delivery.tracking.domain.event.DeliveryPickUpEvent,delivery-fulfilled-event:com.algaworks.algadelivery.delivery.tracking.domain.event.DeliveryFulfilledEvent